name: Auto Rule Generation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml pyyaml
      - name: Generate ChinaASN.list
        run: |
          python scripts/ChinaASN.py
      - name: Generate Scholar.list
        run: |
          python scripts/Scholar.py
      - name: Generate Speedtest.list
        run: |
          python scripts/Speedtest.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update rule lists
